# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  connection-timeout: 5000ms
  servlet:
    context-path: /logMonitor

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    #MySQL配置
        driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.195.244.72:3306/gdgat_tymsywpt_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: root
    # 正式库
#    url: jdbc:mysql://10.195.244.72:3306/gdgat_tymsywpt_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: root
    # 测试库
#    url: jdbc:mysql://10.194.186.223:3306/gdgat_tymsywpt_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: vXd7Qf@5n
#        url: jdbc:mysql://localhost:3306/gongan_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#        username: root
#        password: root
        # 腾讯云测试库
        url: jdbc:mysql://gz-cdb-ilbf4sqp.sql.tencentcdb.com:61930/gdgat_zhxms_tyywfwpt?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: msjw@123
    #oracle配置
    #    driverClassName: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@47.100.206.162:1521:xe
    #    username:
    #    password:
    #SQLServer配置
    #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=
    #    username: sa
    #    password: 123456
    #PostgreSQL配置
  #    driverClassName: org.postgresql.Driver
  #    url: jdbc:postgresql://192.168.10.10:5432/
  #    username: postgres
  #    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/



mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.com.bmsoft.log.monitor.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'





pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
bmsoft:
  database: mysql

  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: localhost
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

idWoker:
  worker-id: 1
  datacenter-id: 1