spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            #driver-class-name: com.mysql.jdbc.Driver
            #url: jdbc:mysql://gz-cdb-ilbf4sqp.sql.tencentcdb.com:61930/gdgat_zhxms_tyywfwpt?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
            #username: root
            #password: msjw@123
            driver-class-name: com.huawei.gauss.jdbc.ZenithDriver
            url: jdbc:zenith:@10.192.64.82:1888?useSSL=false
            username: gdga_tyyw
            password: Gdga0001
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #Oracle需要打开注释
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filters: stat
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
        host: 10.194.186.222
        port: 6379
        #cluster:
         #   nodes:
         #       - 10.194.186.224:7001
         #       - 10.194.186.223:7002
         #       - 10.194.186.222:7003
         #       - 10.194.186.224:7004
         #       - 10.194.186.223:7005
         #       - 10.194.186.222:7006
         #   max-redirects: 3  # 获取失败 最大重定向次数
        database: 0
        password:  #连接密码
        timeout: 6000ms  # 连接超时时长（毫秒）
        jedis:
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接


##多数据源的配置
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=renren_security
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/renren_security
#      username: renren
#      password: 123456

# sftp 附件服务
sftp:
    client:
        protocol: sftp
        host: 10.194.186.222
        port: 22
        username: sftp
        password: gat@test
        # 实际根目录：/sftp/document
        root: /document
        privateKey:
        passphrase:
        # ask | yes | no
        sessionStrictHostKeyChecking: no
        sessionConnectTimeout: 20000
        channelConnectedTimeout: 20000